import choice from './read_line.js';
import select from './select.js';
import insert from './insert.js';
import update from './update.js';
import remove from './delete.js';
import where from './where.js';
import api from './api.js';
select();
insert();
update();
remove();
where();
api();
